word_filters:insert{'балку'}
word_filters:insert{'бассейн'}
word_filters:insert{'венера'}
word_filters:insert{'водопад'}
word_filters:insert{'вулкан'}
word_filters:insert{'гора'}
word_filters:insert{'город'}
word_filters:insert{'джунгли'}
word_filters:insert{'закат'}
word_filters:insert{'звузды'}
word_filters:insert{'земля'}
word_filters:insert{'кирпич'}
word_filters:insert{'космос'}
word_filters:insert{'котловина'}
word_filters:insert{'курган'}
word_filters:insert{'лощина'}
word_filters:insert{'луна'}
word_filters:insert{'метель'}
word_filters:insert{'млечный путь'}
word_filters:insert{'море'}
word_filters:insert{'небо'}
word_filters:insert{'озеро'}
word_filters:insert{'окоп'}
word_filters:insert{'парк'}
word_filters:insert{'пещера'}
word_filters:insert{'плутон'}
word_filters:insert{'пляж'}
word_filters:insert{'поле'}
word_filters:insert{'прерия'}
word_filters:insert{'равнина'}
word_filters:insert{'рассвет'}
word_filters:insert{'река'}
word_filters:insert{'ров'}
word_filters:insert{'роща'}
word_filters:insert{'ручей'}
word_filters:insert{'сад'}
word_filters:insert{'седловина'}
word_filters:insert{'сельва'}
word_filters:insert{'скалы'}
word_filters:insert{'снег'}
word_filters:insert{'солнце'}
word_filters:insert{'степь'}
word_filters:insert{'тайга'}
word_filters:insert{'трава'}
word_filters:insert{'туман'}
word_filters:insert{'тунель'}
word_filters:insert{'улица'}
word_filters:insert{'холм'}
word_filters:insert{'хребет'}
word_filters:insert{'юпитер'}
